name: VM Test
on:
  push:
    branches:
      - main
    paths:
      - 'pkg/fanal/vm/**'
      - 'pkg/fanal/walker/vm.go'
      - 'pkg/fanal/artifact/vm/**'
      - 'integration/vm_test.go'
  pull_request:
    paths:
      - 'pkg/fanal/vm/**'
      - 'pkg/fanal/walker/vm.go'
      - 'pkg/fanal/artifact/vm/**'
      - 'integration/vm_test.go'

jobs:
  vm-test:
    name: VM Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run vm integration tests
        run: |
          make test-vm-integration